version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t nginxgw:latest --build-arg
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  commit:
    jobs:
      - build
